targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/models/{{file}}.dart': 'lib/models/generated/{{file}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/models/{{file}}.dart': 'lib/models/generated/{{file}}.freezed.dart'