// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqurxN0HL5xPSMkLOBDLnNvz4O5U2sH54',
    appId: '1:441648971518:android:863ca05fcf616467ac6faf',
    messagingSenderId: '441648971518',
    projectId: 'myopamp-14c20',
    storageBucket: 'myopamp-14c20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUQN1PIButD0AC6DBPUhmdNQsCRVs9M9g',
    appId: '1:709894266438:ios:ca00647328e1c53b2c7447',
    messagingSenderId: '709894266438',
    projectId: 'myesp32-e60de',
    databaseURL: 'https://myesp32-e60de-default-rtdb.firebaseio.com',
    storageBucket: 'myesp32-e60de.appspot.com',
    androidClientId: '709894266438-ac9s0qc4h1oppeqfega25p24k74gitpg.apps.googleusercontent.com',
    iosClientId: '709894266438-e70dv93u3mgobu53ukmc8pgv01t6gbbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterSaver',
  );
}